name: Build

on: ["push", "pull_request"]

jobs:
  building:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get -yqq install nasm gcc binutils make

      - name: Make
        run: make
